FROM node:20-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm ci --omit=dev

# Copiar código fuente
COPY . .

# Seguridad: no correr como root
RUN chown -R node:node /app
USER node

EXPOSE 3001

CMD ["node", "server.js"]