apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/xander4234/agx/frontend:419883e383a06ac523ad5c2185807dbdaf1a98f9
          imagePullPolicy: Always
          ports:
            - containerPort: 80