apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/xander4234/agx/frontend:a720bf392ef92b1b852cc7b8fab45fb0c4a0a5e0
          imagePullPolicy: Always
          ports:
            - containerPort: 80