apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/xander4234/agx/frontend:0427014359620cb78a62e6cabfc2c431d7695e01
          imagePullPolicy: Always
          ports:
            - containerPort: 80