apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  PORT: "3001"
  PGHOST: "postgres-service"  # ← nombre del Service de PostgreSQL en k8s
  PGPORT: "5432"              # ← puerto estándar interno (no el 5435 de docker-compose)
  PGUSER: "agx"
  PGDATABASE: "agx_health"