apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/xander4234/agx/server:355f7d8e680bd7e757ce37788fc45a85182b7c03
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: server-config
            
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: JWT_SECRET
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: PGPASSWORD
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: OPENAI_API_KEY